application {
    name = "paraiso_api"
    version = "v1"
}

server {
    id = "server-1"
    address = "127.0.0.1"
}

mongodb {
    url = ${?MONGO_URL}
    database = "ekoes"
}

redis {
    url = ${?REDIS_URL}
}

auth {
    auth0Domain = "dev-rikg51ml7pz71iwk.us.auth0.com"
    auth0Audience = "https://ekoes.io/"
    internalSyncSecret = ${?INTERNAL_SYNC_SECRET}
}

api {
    mainHost = "ekoes.io"
    altHost = "www.ekoes.io"
    frontendHost = "localhost:5173"
    frontendPreviewHost = "localhost:4173"
    backendHost = "localhost:8080"
    scheme = "https"
    secretEncryptKey = ${?SECRET_ENCRYPT_KEY}
    secretSignKey = ${?SECRET_SIGN_KEY}
}